name: Build and deploy to AWS S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  
      
    - name: Build project
      run: cd ./KpiSchedule.Frontend && dotnet publish -c Release
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::251999958052:role/kpi-schedule-github-actions-role
        aws-region: eu-central-1
    
    - name: Deploy to S3
      run: cd ./KpiSchedule.Frontend/bin/Release/net6.0/publish/wwwroot && aws s3 sync . s3://kpi-schedule-frontend/ --delete
